"""Add processing progress to Video

Revision ID: 8704bd5d94a9
Revises: ef14dc3ccca2
Create Date: 2026-02-21 13:29:32.141868

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8704bd5d94a9"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "ef14dc3ccca2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("videos", sa.Column("processing_status", sa.String(), nullable=True))
    op.add_column("videos", sa.Column("processing_progress", sa.Float(), nullable=True))
    op.add_column("videos", sa.Column("processed_at", sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("videos", "processed_at")
    op.drop_column("videos", "processing_progress")
    op.drop_column("videos", "processing_status")
    # ### end Alembic commands ###
